language: R
r:
 - 3.4.0
 - release
# - devel # Incompatible with devtools
cache: packages
sudo: required # required if r_binary_packages; false otherwise
warnings_are_errors: true
r_check_args: --as-cran

git:
  depth: 1

r_github_packages:
 - ms609/TreeDist # Remove once available via CRAN

r_binary_packages:
 - devtools
 - Rdpack
 - roxygen2
 - testthat

before_script:
  - R -e "devtools::document()"
