language: r
os: linux
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
git:
  depth: 1

jobs:
  include:
    - r: devel
      r_binary_packages:
       - devtools
       - Rdpack
       - roxygen2
      after_success:
        - Rscript -e "covr::codecov()"

r_packages:
 - TreeTools

r_github_packages:
 - ms609/TreeDist # Remove once available via CRAN
 - ms609/TreeSearch # Remove once available via CRAN
 - ms609/TBRDist # Remove once available via CRAN

before_script:
  - R -e "pkgload::load_all(); devtools::document()"
