language: r
os: linux
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
git:
  depth: 1

jobs:
  include:
    - r: devel
      after_success:
        - Rscript -e "covr::codecov()"
    - r: release
      before_install:
        - sudo apt-get -y install libharfbuzz-dev libfribidi-dev
      #r_binary_packages:
      # - benchmarkme
      # - binom
      # - bookdown
      # - colorspace
      # - devtools
      # - knitr
      # - MASS
      # - microbenchmark
      # - phangorn
      # - Rdpack
      # - rmarkdown
      # - roxygen2
      # - spatstat
      # - testthat
      r_packages:
        - devtools
        - freetypeharfbuzz
        - pkgdown
        - Rdpack
      r_github_packages:
        - ms609/TreeDist
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        cleanup: false
        skip_cleanup: true
    - r: 3.6.0 # phangorn requires 3.6.0
    - os: osx
      r: release
      r_github_packages:
        - ms609/TreeDist
      before_install:
        - sudo tlmgr install doi titling hyperref
  allow_failures:
    r: devel # Freezing in tests; cannot diagnose

r_packages:
  - devtools

before_script:
  - R -e "pkgload::load_all(); devtools::document()"
