language: r
os: linux
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
git:
  depth: 1

jobs:
  include:
    - r: 3.5.0
      r_packages:
       - devtools
       - testthat
    - r: release
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      r_binary_packages:
       - benchmarkme
       - binom
       - bookdown
       - colorspace
       - devtools
       - knitr
       - MASS
       - microbenchmark
       - phangorn
       - Rdpack
       - rmarkdown
       - roxygen2
       - spatstat
       - testthat
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        cleanup: false
        skip_cleanup: true
    - r: devel
      r_binary_packages:
       - covr
       - devtools
       - roxygen2
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      r: release
      r_packages:
        - devtools
        - Rdpack
        - roxygen2
        - testthat
      before_install:
      - brew install cairo
      - sudo tlmgr install doi titling hyperref
  allow_failures:
    r: devel # Freezing in tests; cannot diagnose

r_github_packages:
 - ms609/TreeDist # Remove once available via CRAN
 - ms609/TBRDist # Remove once available via CRAN

before_script:
  - R -e "pkgload::load_all(); devtools::document()"
