---
title: "One tip distant"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
csl: ../inst/apa-old-doi-prefix.csl
vignette: >
  %\VignetteIndexEntry{One tip distant}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

We will add a tip to every location on a backbone tree:
```{R backbone, echo=FALSE, fig.width=7.2, fig.asp=0.5, message=FALSE}
library('Quartet')
library('TreeDist')
library('TreeDistData')
backbone <- ape::read.tree(text='(a, (b, (c, (d, (((e, f), g), (h, (i, j)))))));')
par(mar = rep(0, 4))
plot(backbone)
nTip <- length(backbone$tip.label)
newTrees <- TreeTools::AddTipEverywhere(backbone)

```


The expected distance is the number of edges separating one tip addition 
location from each other.

```{r, echo=FALSE, fig.width=7.2, fig.asp=2, message=FALSE}
ordr <- order(backbone$edge[, 2])[-(nTip + 1L)]
dists <- TreeTools::EdgeDistances(backbone)[ordr, ordr]
```

We would like a metric to display a monotonic increase, such that all tree pairs
with _n_ edges between the added leaves are further apart than any tree pair
with _n_ &minus; 1 edges between the added leaves.

```{r, echo=FALSE, fig.width=7.2, fig.asp=2, message=FALSE}
BoxPlot <- function (d, method) {
  boxplot(d ~ dists, border = TreeDistCol(method), xlab = '', ylab = '')
  mtext(tdAbbrevs[method], 2, line = 2, cex=0.8)
  mtext('Edges between added leaves', 1, line = 2, cex=0.8)
}

par(mfrow=c(4, 2), mar=c(3.5, 3.5, 0, 0.5), line = 0)
BoxPlot(DifferentPhylogeneticInfo(newTrees), 'dpi')
BoxPlot(ClusteringInfoDistance(newTrees), 'cid')
BoxPlot(NyeTreeSimilarity(newTrees, similarity = FALSE), 'nts')
BoxPlot(MatchingSplitDistance(newTrees), 'msd')
BoxPlot(QuartetDivergence(QuartetStatus(newTrees)), 'qd')

path <- matrix(0, length(newTrees), length(newTrees))
for (i in seq_along(newTrees))
  for (j in seq_along(newTrees))
    path[i, j] <- phangorn::path.dist(newTrees[[i]], newTrees[[j]])
BoxPlot(path, 'path')

spr <- matrix(0, length(newTrees), length(newTrees))
for (i in seq_along(newTrees))
  for (j in seq_along(newTrees))
    spr[i, j] <- phangorn::SPR.dist(newTrees[[i]], newTrees[[j]])
BoxPlot(spr, 'spr')

BoxPlot(TreeDist::RobinsonFoulds(newTrees), 'rf')
```

